### PR TITLE
added mapLoadingIndicator plugin to address noncritical error; fixed …

### LINKED ISSUE #17: Uncaught TypeError: feature.getStyle is not a function
TypeError: feature.getStyle is not a function
Select.applySelectedStyle_
/src/interaction/Select.js:410
  407 |  * @private
  408 |  */
  409 | Select.prototype.removeFeatureLayerAssociation_ = function (feature) {
> 410 |     delete this.featureLayerAssociation_[getUid(feature)];
      | ^  411 | };
  412 | /**
  413 |  * Handles the {@link module:ol/MapBrowserEvent map browser event} and may change the
View compiled
Select.addFeature_
/src/interaction/Select.js:381
  378 | Select.prototype.applySelectedStyle_ = function (feature) {
  379 |     var key = getUid(feature);
  380 |     if (!(key in originalFeatureStyles)) {
> 381 |         originalFeatureStyles[key] = feature.getStyle();
      | ^  382 |     }
  383 |     feature.setStyle(this.style_);
  384 | };
View compiled
Collection.Target.dispatchEvent
/src/events/Target.js:110
  107 |     dispatching[type] = 0;
  108 |     pendingRemovals[type] = 0;
  109 | }
> 110 | ++dispatching[type];
      | ^  111 | for (var i = 0, ii = listeners.length; i < ii; ++i) {
  112 |     if ('handleEvent' in listeners[i]) {
  113 |         propagate = /** @type {import("../events.js").ListenerObject} */ (listeners[i]).handleEvent(evt);
View compiled
Collection.insertAt
src/Collection.js:203
  200 |     this.array_.splice(index, 0, elem);
  201 |     this.updateLength_();
  202 |     this.dispatchEvent(new CollectionEvent(CollectionEventType.ADD, elem, index));
> 203 | };
      | ^  204 | /**
  205 |  * Remove the last element of the collection and return it.
  206 |  * Return `undefined` if the collection is empty.
View compiled
Collection.push
https://localhost:3000/static/js/vendors~main.chunk.js:201006:10
  201003 |   }
  201004 | 
  201005 |   var n = this.getLength();
> 201006 |   this.insertAt(n, elem);
         |        ^  201007 |   return this.getLength();
  201008 | };
  201009 | /**
View source
Collection.extend
src/Collection.js:140
  137 |  * to the end of the collection.
  138 |  * @param {!Array<T>} arr Array.
  139 |  * @return {Collection<T>} This collection.
> 140 |  * @api
      | ^  141 |  */
  142 | Collection.prototype.extend = function (arr) {
  143 |     for (var i = 0, ii = arr.length; i < ii; ++i) {
View compiled
Select.handleEvent
/src/interaction/Select.js:502
  499 |             this.dispatchEvent(new SelectEvent(SelectEventType.SELECT, selected, deselected, mapBrowserEvent));
  500 |         }
  501 |         return true;
> 502 |     };
  503 |     return Select;
  504 | }(Interaction));
  505 | /**
View compiled
▼ 3 stack frames were expanded.
Map.PluggableMap.handleMapBrowserEvent
node_modules/@corpsmap/corpsmap/lib/dev.js:45810
MapBrowserEventHandler.Target.dispatchEvent
node_modules/@corpsmap/corpsmap/lib/dev.js:6604
MapBrowserEventHandler.<anonymous>
node_modules/@corpsmap/corpsmap/lib/dev.js:42423
▲ 3 stack frames were expanded.

Replicable by fast clicking on different states.

### PR DESCRIPTION
**Pull request by trietmnj**
…incompatibility between Select interaction and the VTL default RenderFeature; fixed #17

### CODE REVIEW

File: src/cm-plugins/download/cm3-download-bundle.js [hunk 1]
```diff
@@ -88,46 +83,55 @@ const initMap=function(store){
...
       selectSingleClick.getFeatures().clear(); // clear selected state
       return false;
     }
 
-    // Map closeDownPopUp to cancel button
-    closer.onclick = closeDownPopUp;
+    // if clicked on the state mask, evt is a SelectEvent obj
+    // if clicked on vtl, evt is a RenderFeature obj
+    // RenderFeature is not compatible with Select(), solution is to switch to 
+    // https://github.com/openlayers/openlayers/issues/9840
```
Comment (HenryGeorgist) [inline src/cm-plugins/download/cm3-download-bundle.js:99]: Good reference. This seems interesting. I will download source and test it out later - thanks for researching this.

**Review by HenryGeorgist — APPROVED** [review]
